In [ ]:
import numpy as np

print(np.random.randint(low=1,high=20,size=(10)))

[ 1  9  7 12 19  7  8  6 16 16]


In [17]:
import torch
import numpy as np
np.random.seed(42)
a=np.random.randint(1,10,size=(4,4))
b=torch.from_numpy(a)
print(a)
a[:2,2:]=3
print(a)
a[2:,:2]=3
print(b)
print(torch.linalg.det(b.float()))


[[7 4 8 5]
 [7 3 7 8]
 [5 4 8 8]
 [3 6 5 2]]
[[7 4 3 3]
 [7 3 3 3]
 [5 4 8 8]
 [3 6 5 2]]
tensor([[7, 4, 3, 3],
        [7, 3, 3, 3],
        [3, 3, 8, 8],
        [3, 3, 5, 2]])
tensor(141.0000)


In [4]:
import torch
import numpy as np
np.random.seed(42)
a=np.random.randint(1,10,size=(4,4))
b=torch.from_numpy(a)
print(a)
c=torch.ones_like(b)
print(b@b.T)

[[7 4 8 5]
 [7 3 7 8]
 [5 4 8 8]
 [3 6 5 2]]
tensor([[154, 157, 155,  95],
        [157, 171, 167,  90],
        [155, 167, 169,  95],
        [ 95,  90,  95,  74]])


In [6]:
import numpy as np
np.random.seed(42)
for i in range(1,5):
    print(np.zeros((i,i)))

[[0.]]
[[0. 0.]
 [0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
