In [ ]:
import torch
torch.manual_seed(42)
x=torch.ones(3,3,dtype=torch.int)
b=torch.zeros_like(x)
c=torch.randint(1,10,size=(3,3))
a=torch.cat([x,b,c],dim=0)
print(a)
print(a.shape,a.device)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [7, 6, 8],
        [5, 1, 3],
        [8, 6, 5]])
torch.Size([9, 3]) cpu


In [ ]:
import numpy as np 
np.random.seed(42)
a=np.random.randn(3,3,3)
print(a)

[[[0.37454012 0.95071431 0.73199394]
  [0.59865848 0.15601864 0.15599452]
  [0.05808361 0.86617615 0.60111501]]

 [[0.70807258 0.02058449 0.96990985]
  [0.83244264 0.21233911 0.18182497]
  [0.18340451 0.30424224 0.52475643]]

 [[0.43194502 0.29122914 0.61185289]
  [0.13949386 0.29214465 0.36636184]
  [0.45606998 0.78517596 0.19967378]]]


In [9]:
import numpy as np
import torch
np.random.seed(42)
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr_3=np.random.randint(1,10,size=(2,2,3))
print(f"차원:{arr_3.ndim}")
print(f"타입{arr_3.dtype}")
print(f"형태{arr_3.shape}")
print(f"{arr_3.size}")

차원:3
타입int64
형태(2, 2, 3)
12


In [12]:
import numpy as np
import torch
np.random.seed(42)
a=np.random.randint(1,10,size=(4,4))
print(a)
flat=a.argmax()
row=a.argmax(axis=0)
col=a.argmax(axis=1)
print(f"행으로볼떄{row}")
print(f"열으로볼때{col}")
print(f"평탄화했을때{flat}")
print(a.sum())
print(a.sum(axis=0))
print(a.mean())
print(a.mean(axis=1))
print(a.std())
print(a.std(axis=0))
print(a.var())
print(a.var(axis=1))

[[7 4 8 5]
 [7 3 7 8]
 [5 4 8 8]
 [3 6 5 2]]
행으로볼떄[0 3 0 1]
열으로볼때[2 3 2 1]
평탄화했을때2
90
[22 17 28 23]
5.625
[6.   6.25 6.25 4.  ]
1.964529205687714
[1.6583124  1.08972474 1.22474487 2.48746859]
3.859375
[2.5    3.6875 3.1875 2.5   ]


In [ ]:
arrr_1=np.ones([3,3])

arr_F=np.full((3,3),2)
ref=np.ones_like(arr_F)


In [9]:
import numpy as np 

num1=np.arange(0,9).reshape(3,3)
print(num1)
print(num1.shape)
print(num1.dtype)
print(num1.ndim)
print(num1.size)
u,s,vt=np.linalg.svd(num1)
ze=np.diag(s)
print(np.allclose(u@ze@vt, num1))


[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)
int64
2
9
True


In [15]:
arr_1=np.arange(9)
print(arr_1)
arr_1=arr_1.reshape(3,3)
print(arr_1)
print(arr_1[:,:2])

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1]
 [3 4]
 [6 7]]


In [17]:
import numpy as  np
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1[0,:])
print(arr1[0,1])

[1 2 3]
2


In [8]:
import numpy as np
arr=np.arange(9).reshape(3,3)
arr[1,:]*=10
print(arr)
arr[2,1:]+=10
print(arr@arr.T)

[[ 0  1  2]
 [30 40 50]
 [ 6  7  8]]
[[   5  140   53]
 [ 140 5000 1760]
 [  53 1760  649]]


In [22]:
arr3=np.arange(50).reshape(5,10)
print(arr3)
print(arr3[:,0][::2])



[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[ 0 20 40]


In [28]:
arr4=np.arange(18).reshape(3,6)
print(arr4)
print(arr4[1:,[1,3,5]])
print(arr4.T)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[[ 7  9 11]
 [13 15 17]]
[[ 0  6 12]
 [ 1  7 13]
 [ 2  8 14]
 [ 3  9 15]
 [ 4 10 16]
 [ 5 11 17]]


In [ ]:
np.random.seed(42)
ran=np.random.randint(-10,10,size=(4,4))
print(ran)
print(np.where(ran>0,ran,0))


[[-4  9  4  0]
 [-3 -4  8  0]
 [ 0 -7 -3 -8]
 [-9  1 -5 -9]]
2


In [60]:
arr7=np.array([[6,9,6,8,7],[2,3,5,4,1]])

print(np.argmax(arr7,axis=1))

[1 2]


In [65]:
arr8=np.array([[1,2,3],[4,5,6]])
mean=np.mean(arr8,axis=0)
std=np.std(arr8,axis=0)
nomarl=(arr8-mean)/std
print(nomarl)

[[-1. -1. -1.]
 [ 1.  1.  1.]]


In [ ]:
import numpy as np
np.random.seed(42)
p1=np.arange(1,51,3)
print(p1)
p2=np.eye(4)*7
print(p2)
p3=np.random.randn(4,4)
print(np.sum(p3,axis=0),np.sum(p3,axis=1))
p4=np.random.randint(1,16,size=(4,4))
print(p4)
p4[0]=p4[0][::-1]
p4[1]=p4[1][::-1]
p4[2]=p4[2][::-1]
p4[3]=p4[3][::-1]

print(p4.diagonal())
p5=np.random.randint(-10,10,size=10)
print(p5)
som=np.sum(np.where(p5>0,p5,0))
print(som)
p6=np.random.randn(2,3)
print(p6@p6.T)
p7=np.random.randint(1,100,size=20)
print(p7)
print(np.unique(p7))
p8=np.random.rand(10)
print(np.sort(p8))

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]
[[7. 0. 0. 0.]
 [0. 7. 0. 0.]
 [0. 0. 7. 0.]
 [0. 0. 0. 7.]]
[ 0.03504866 -1.74312146  0.03856583  1.2624473 ] [ 2.52916825  1.87835721 -0.85606179 -3.95852333]
[[11 15 10 12]
 [12 15 14 14]
 [15 14  3 12]
 [ 7  4  9  3]]
[12 14 14  7]
[-6  8 -4 -2 -4  7 -7  3  7 -2]
25
[[ 3.0969732  -0.59339879]
 [-0.59339879  1.63132754]]
