In [ ]:
import torch
torch.manual_seed(42)
x=torch.ones(3,3,dtype=torch.int)
b=torch.zeros_like(x)
c=torch.randint(1,10,size=(3,3))
a=torch.cat([x,b,c],dim=0)
print(a)
print(a.shape,a.device)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [7, 6, 8],
        [5, 1, 3],
        [8, 6, 5]])
torch.Size([9, 3]) cpu


In [ ]:
import numpy as np 
np.random.seed(42)
a=np.random.randn(3,3,3)
print(a)

[[[0.37454012 0.95071431 0.73199394]
  [0.59865848 0.15601864 0.15599452]
  [0.05808361 0.86617615 0.60111501]]

 [[0.70807258 0.02058449 0.96990985]
  [0.83244264 0.21233911 0.18182497]
  [0.18340451 0.30424224 0.52475643]]

 [[0.43194502 0.29122914 0.61185289]
  [0.13949386 0.29214465 0.36636184]
  [0.45606998 0.78517596 0.19967378]]]


In [9]:
import numpy as np
import torch
np.random.seed(42)
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr_3=np.random.randint(1,10,size=(2,2,3))
print(f"차원:{arr_3.ndim}")
print(f"타입{arr_3.dtype}")
print(f"형태{arr_3.shape}")
print(f"{arr_3.size}")

차원:3
타입int64
형태(2, 2, 3)
12


In [12]:
import numpy as np
import torch
np.random.seed(42)
a=np.random.randint(1,10,size=(4,4))
print(a)
flat=a.argmax()
row=a.argmax(axis=0)
col=a.argmax(axis=1)
print(f"행으로볼떄{row}")
print(f"열으로볼때{col}")
print(f"평탄화했을때{flat}")
print(a.sum())
print(a.sum(axis=0))
print(a.mean())
print(a.mean(axis=1))
print(a.std())
print(a.std(axis=0))
print(a.var())
print(a.var(axis=1))

[[7 4 8 5]
 [7 3 7 8]
 [5 4 8 8]
 [3 6 5 2]]
행으로볼떄[0 3 0 1]
열으로볼때[2 3 2 1]
평탄화했을때2
90
[22 17 28 23]
5.625
[6.   6.25 6.25 4.  ]
1.964529205687714
[1.6583124  1.08972474 1.22474487 2.48746859]
3.859375
[2.5    3.6875 3.1875 2.5   ]


In [ ]:
arrr_1=np.ones([3,3])

arr_F=np.full((3,3),2)
ref=np.ones_like(arr_F)
