In [4]:
import numpy as np
import torch

rand=torch.rand([2,3])
print(rand)

tensor([[0.9023, 0.8174, 0.0122],
        [0.1730, 0.2148, 0.7690]])


In [10]:
torch.manual_seed(42)
rand_int_x=torch.randint(low=1,high=10,size=(3,3))
rand_int_y=torch.randint(low=2,high=9,size=(3,3))
print(f"x의값:\n{rand_int_x}\n")
print(f"x의값:\n{rand_int_y}\n")
print(rand_int_x@rand_int_y.T)

x의값:
tensor([[7, 6, 8],
        [5, 1, 3],
        [8, 6, 5]])

x의값:
tensor([[2, 2, 7],
        [8, 6, 3],
        [4, 8, 8]])

tensor([[ 82, 116, 140],
        [ 33,  55,  52],
        [ 63, 115, 120]])


In [16]:
np.random.seed(42)
num=np.random.randint(1,10,(3,3))
num_float=np.random.rand(3,3)
print(f"{num}\n")
print(f"{num_float}\n")

[[7 4 8]
 [5 7 3]
 [7 8 5]]

[[0.60111501 0.70807258 0.02058449]
 [0.96990985 0.83244264 0.21233911]
 [0.18182497 0.18340451 0.30424224]]



In [17]:
torch_refer_numpy=torch.from_numpy(num)
print(f"{torch_refer_numpy}\n")
print(f"{torch_refer_numpy.shape}")

tensor([[7, 4, 8],
        [5, 7, 3],
        [7, 8, 5]])

torch.Size([3, 3])
