In [14]:
import torch

In [15]:
torch.manual_seed(42)

In [16]:
a=torch.tensor((3,3))
print(a)

tensor([3, 3])


In [ ]:
four=torch.randn(4, 4)


tensor([[ 1.9269,  1.4873,  0.9007, -2.1055],
        [ 0.6784, -1.2345, -0.0431, -1.6047],
        [-0.7521,  1.6487, -0.3925, -1.4036],
        [-0.7279, -0.5594, -0.7688,  0.7624]])

In [22]:
b=torch.randint(1,4,size=(2,5))
b

tensor([[3, 2, 1, 2, 2],
        [3, 2, 3, 3, 2]])

In [25]:
c=torch.randint(1,4,size=(5,2))
k=c@b

In [27]:
print(torch.linalg.det(k.float()))

tensor(0.)


In [28]:
import torch
import torch.nn as nn 
import torch.nn.functional as f
import torch.optim as optim
import torch.utils.data as data 

import torchvision.transforms as transforms
import torchvision.datasets as datasets

from sklearn import metrics
from sklearn import decomposition
from sklearn import manifold
from tqdm.notebook import trange,tqdm
import matplotlib.pyplot as plt 
import numpy as np
import copy 
import random 
import time

In [ ]:
seed=42 

random.seed(seed)
np.random.seed(42)
torch.manual_seed(42)
torch.cuda.manual_seed(42)
torch.backends.cudnn.deterministic=True