# 1일차: NumPy 기본과 선형대수 도입

## 학습 목표
- 파이썬에서 NumPy 배열을 다루는 방법 익히기
- 벡터와 행렬 등 선형대수 기본 개념 이해
- 파이썬 리스트와 NumPy 배열의 차이점 파악
- 간단한 산술 연산과 행렬의 차원(shape) 개념 학습

## 💡 이론 개요

### NumPy란?
NumPy는 파이썬의 과학 계산 라이브러리로, **다차원 배열(ndarray)**을 효율적으로 다룰 수 있습니다.

### 주요 개념
- **배열의 shape(모양)**: 각 차원의 크기를 나타내며, 2x4 배열은 (2, 4) shape을 가집니다
- **벡터(vector)**: 1차원 배열 (예: 길이가 N인 배열)
- **행렬(matrix)**: 2차원 배열
- **동일 자료형**: NumPy 배열은 동일한 자료형의 값들을 담으며 연산에 최적화

### NumPy vs Python 리스트
- NumPy 배열: 원소별 연산 가능, 메모리 연속성으로 성능 우수
- Python 리스트: 원소별 연산 불가 (예: `[1,2,3] + 1`은 에러)

In [2]:
# NumPy 라이브러리 불러오기
import numpy as np

print(f"NumPy 버전: {np.__version__}")

NumPy 버전: 2.2.6


## 📚 1. 배열 생성 기본

### 1.1 리스트로부터 배열 생성

In [3]:
# 1차원 배열 (벡터) 생성
vector = np.array([1, 2, 3, 4, 5])
print("1차원 배열 (벡터):")
print(vector)
print(f"타입: {type(vector)}")
print(f"Shape: {vector.shape}")
print(f"차원 수: {vector.ndim}")
print(f"데이터 타입: {vector.dtype}")
print()

1차원 배열 (벡터):
[1 2 3 4 5]
타입: <class 'numpy.ndarray'>
Shape: (5,)
차원 수: 1
데이터 타입: int64



In [4]:
# 2차원 배열 (행렬) 생성
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("2차원 배열 (행렬):")
print(matrix)
print(f"Shape: {matrix.shape}  # (행, 열) = (2, 3)")
print(f"차원 수: {matrix.ndim}")
print(f"전체 원소 개수: {matrix.size}")
print()

2차원 배열 (행렬):
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)  # (행, 열) = (2, 3)
차원 수: 2
전체 원소 개수: 6



### 💬 설명
- **shape**: (2, 3)은 2행 3열을 의미
- **ndim**: 차원 수 (1차원, 2차원, 3차원 등)
- **size**: 전체 원소 개수 (2 × 3 = 6)
- **dtype**: 데이터 타입 (int64, float64 등)

### 1.2 특수 배열 생성 함수

In [5]:
# 영행렬 생성 (모든 원소가 0)
zeros = np.zeros((3, 4))  # 3x4 영행렬
print("3x4 영행렬:")
print(zeros)
print()

3x4 영행렬:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]



In [6]:
# 일행렬 생성 (모든 원소가 1)
ones = np.ones((2, 3))
print("2x3 일행렬:")
print(ones)
print()

2x3 일행렬:
[[1. 1. 1.]
 [1. 1. 1.]]



In [ ]:
# 단위행렬 생성 (대각선만 1, 나머지 0)
identity = np.eye(4)
print("4x4 단위행렬:")
print(identity)
print()

# 단위행렬의 특징: I @ A = A @ I = A
print("단위행렬은 행렬 곱셈의 항등원입니다.")

In [ ]:
# 범위 배열 생성
range_array = np.arange(0, 10, 2)  # 0부터 10 미만까지 2씩 증가
print("범위 배열 (0, 2, 4, 6, 8):")
print(range_array)
print()

# 균등 간격 배열 생성
linspace_array = np.linspace(0, 1, 5)  # 0부터 1까지 5개의 균등 간격
print("균등 간격 배열 (0부터 1까지 5개):")
print(linspace_array)
print()

## 📚 2. 기본 산술 연산

### 2.1 벡터 연산

In [7]:
# 벡터 덧셈
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 원소별 덧셈
c = a + b
print("벡터 덧셈:")
print(f"a = {a}")
print(f"b = {b}")
print(f"a + b = {c}")
print()

# 계산 과정:
# [1+4, 2+5, 3+6] = [5, 7, 9]

벡터 덧셈:
a = [1 2 3]
b = [4 5 6]
a + b = [5 7 9]



In [8]:
# 스칼라 곱셈 (스칼라와 벡터의 곱)
scalar = 2
result = scalar * c
print("스칼라 곱셈:")
print(f"c = {c}")
print(f"2 * c = {result}")
print()

# 계산 과정:
# 2 * [5, 7, 9] = [2*5, 2*7, 2*9] = [10, 14, 18]

스칼라 곱셈:
c = [5 7 9]
2 * c = [10 14 18]



### 2.2 행렬 연산

In [9]:
# 행렬 생성
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print("행렬 A:")
print(A)
print()
print("행렬 B:")
print(B)
print()

행렬 A:
[[1 2]
 [3 4]]

행렬 B:
[[5 6]
 [7 8]]



In [10]:
# 행렬 덧셈 (원소별)
C = A + B
print("행렬 덧셈 (A + B):")
print(C)
print()

# 계산 과정:
# [[1+5, 2+6],  = [[6, 8],
#  [3+7, 4+8]]     [10, 12]]

행렬 덧셈 (A + B):
[[ 6  8]
 [10 12]]



In [11]:
# 원소별 곱셈 (element-wise multiplication, Hadamard product)
D = A * B
print("원소별 곱셈 (A * B):")
print(D)
print()

# 계산 과정:
# [[1*5, 2*6],  = [[5, 12],
#  [3*7, 4*8]]     [21, 32]]

원소별 곱셈 (A * B):
[[ 5 12]
 [21 32]]



In [ ]:
# 행렬 곱셈 (matrix multiplication)
E = A @ B  # 또는 np.matmul(A, B)
print("행렬 곱셈 (A @ B):")
print(E)
print()

# 계산 과정 (자세히):
# E[0,0] = A[0,:] · B[:,0] = 1*5 + 2*7 = 5 + 14 = 19
# E[0,1] = A[0,:] · B[:,1] = 1*6 + 2*8 = 6 + 16 = 22
# E[1,0] = A[1,:] · B[:,0] = 3*5 + 4*7 = 15 + 28 = 43
# E[1,1] = A[1,:] · B[:,1] = 3*6 + 4*8 = 18 + 32 = 50
#
# 결과: [[19, 22],
#       [43, 50]]

print("\n상세 계산 과정:")
print(f"E[0,0] = {A[0,0]}*{B[0,0]} + {A[0,1]}*{B[1,0]} = {A[0,0]*B[0,0]} + {A[0,1]*B[1,0]} = {E[0,0]}")
print(f"E[0,1] = {A[0,0]}*{B[0,1]} + {A[0,1]}*{B[1,1]} = {A[0,0]*B[0,1]} + {A[0,1]*B[1,1]} = {E[0,1]}")
print(f"E[1,0] = {A[1,0]}*{B[0,0]} + {A[1,1]}*{B[1,0]} = {A[1,0]*B[0,0]} + {A[1,1]*B[1,0]} = {E[1,0]}")
print(f"E[1,1] = {A[1,0]}*{B[0,1]} + {A[1,1]}*{B[1,1]} = {A[1,0]*B[0,1]} + {A[1,1]*B[1,1]} = {E[1,1]}")

### 💬 원소별 곱 vs 행렬 곱

| 연산 | 기호 | 설명 | 결과 크기 |
|------|------|------|----------|
| 원소별 곱 | `A * B` | 같은 위치 원소끼리 곱함 | A와 동일 |
| 행렬 곱 | `A @ B` | 행과 열의 내적 | (m,n) @ (n,p) = (m,p) |

## 📚 3. 배열 속성 확인

In [ ]:
# 다양한 배열 생성하여 속성 확인
arrays = {
    "스칼라": np.array(42),
    "1D 배열": np.array([1, 2, 3, 4]),
    "2D 배열": np.array([[1, 2, 3], [4, 5, 6]]),
    "3D 배열": np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
}

for name, arr in arrays.items():
    print(f"\n{name}:")
    print(f"  값: {arr if arr.ndim <= 2 else '(3D array)'}")
    print(f"  shape: {arr.shape}")
    print(f"  ndim: {arr.ndim}")
    print(f"  size: {arr.size}")
    print(f"  dtype: {arr.dtype}")

### 💬 shape 해석
- `()`: 0차원 (스칼라)
- `(4,)`: 1차원, 길이 4
- `(2, 3)`: 2차원, 2행 3열
- `(2, 2, 2)`: 3차원, 2×2×2

## 📚 4. 데이터 타입 (dtype)

In [ ]:
# 정수 배열
int_array = np.array([1, 2, 3])
print(f"정수 배열: {int_array}, dtype: {int_array.dtype}")

# 실수 배열
float_array = np.array([1.0, 2.5, 3.7])
print(f"실수 배열: {float_array}, dtype: {float_array.dtype}")

# 혼합 시 자동 형변환 (정수 + 실수 = 실수)
mixed_array = np.array([1, 2.5, 3])
print(f"혼합 배열: {mixed_array}, dtype: {mixed_array.dtype}")
print()

In [12]:
# 명시적 형변환
arr = np.array([1.7, 2.3, 3.9])
print(f"원본 (float): {arr}")

arr_int = arr.astype(int)
print(f"정수로 변환: {arr_int}, dtype: {arr_int.dtype}")
print("※ 소수점 이하는 버려집니다 (반올림 아님)")

원본 (float): [1.7 2.3 3.9]
정수로 변환: [1 2 3], dtype: int64
※ 소수점 이하는 버려집니다 (반올림 아님)


## 🔥 연습 문제

### 문제 1: 배열 생성과 기본 연산

In [ ]:
# TODO: 다음 작업을 수행하세요
# 1. 벡터 v1 = [10, 20, 30], v2 = [1, 2, 3] 생성
# 2. v1 + v2 계산
# 3. v1 - v2 계산
# 4. 3 * v1 계산

# 여기에 코드 작성


In [ ]:
# 해답
v1 = np.array([10, 20, 30])
v2 = np.array([1, 2, 3])

print("1. 벡터 생성:")
print(f"v1 = {v1}")
print(f"v2 = {v2}")
print()

print("2. v1 + v2:")
result_add = v1 + v2
print(f"{result_add}")
print(f"계산: [10+1, 20+2, 30+3] = [11, 22, 33]")
print()

print("3. v1 - v2:")
result_sub = v1 - v2
print(f"{result_sub}")
print(f"계산: [10-1, 20-2, 30-3] = [9, 18, 27]")
print()

print("4. 3 * v1:")
result_mul = 3 * v1
print(f"{result_mul}")
print(f"계산: [3*10, 3*20, 3*30] = [30, 60, 90]")

### 문제 2: 행렬 생성과 연산

In [ ]:
# TODO: 다음 작업을 수행하세요
# 1. 3x3 행렬 M1 = [[1,2,3], [4,5,6], [7,8,9]] 생성
# 2. 3x3 단위행렬 I 생성
# 3. M1 + I 계산
# 4. M1 * 2 계산

# 여기에 코드 작성
M1=np.array([[1,2,3],[4,5,6],[7,8,9]])
I=np.eye(3)
result_1=M1+I
reult_2=M1*2
print(M1)
print(I)
print(result_1)
print(reult_2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [ ]:
# 해답
M1 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
I = np.eye(3)

print("1. 행렬 M1:")
print(M1)
print()

print("2. 단위행렬 I:")
print(I)
print()

print("3. M1 + I:")
result = M1 + I
print(result)
print("※ 대각선 원소에만 1이 더해집니다")
print()

print("4. M1 * 2:")
result2 = M1 * 2
print(result2)
print("※ 모든 원소가 2배가 됩니다")

### 문제 3: 속성 확인

In [37]:
# TODO: 다음 배열들의 shape, ndim, dtype를 출력하세요
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1.5, 2.5], [3.5, 4.5]])
arr3 = np.zeros((2, 3, 4))

# 여기에 코드 작성
print(f"{arr1.shape},{arr1.ndim},{arr1.dtype}")
print(f"{arr2.shape},{arr2.ndim},{arr2.dtype}")
print(f"{arr3.shape},{arr3.ndim},{arr3.dtype}")
print(arr3)


(5,),1,int64
(2, 2),2,float64
(2, 3, 4),3,float64
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [17]:
# 해답
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1.5, 2.5], [3.5, 4.5]])
arr3 = np.zeros((2, 3, 4))

print("arr1 속성:")
print(f"  값: {arr1}")
print(f"  shape: {arr1.shape} → 1차원, 길이 5")
print(f"  ndim: {arr1.ndim} → 1차원 배열")
print(f"  dtype: {arr1.dtype} → 정수형")
print()

print("arr2 속성:")
print(f"  값:\n{arr2}")
print(f"  shape: {arr2.shape} → 2행 2열")
print(f"  ndim: {arr2.ndim} → 2차원 배열")
print(f"  dtype: {arr2.dtype} → 실수형")
print()

print("arr3 속성:")
print(f"  shape: {arr3.shape} → 2×3×4 3차원 배열")
print(f"  ndim: {arr3.ndim} → 3차원 배열")
print(f"  dtype: {arr3.dtype} → 실수형")
print(f"  총 원소 개수: {arr3.size} (2×3×4=24)")

arr1 속성:
  값: [1 2 3 4 5]
  shape: (5,) → 1차원, 길이 5
  ndim: 1 → 1차원 배열
  dtype: int64 → 정수형

arr2 속성:
  값:
[[1.5 2.5]
 [3.5 4.5]]
  shape: (2, 2) → 2행 2열
  ndim: 2 → 2차원 배열
  dtype: float64 → 실수형

arr3 속성:
  shape: (2, 3, 4) → 2×3×4 3차원 배열
  ndim: 3 → 3차원 배열
  dtype: float64 → 실수형
  총 원소 개수: 24 (2×3×4=24)


### 문제 4: 행렬 곱셈 이해

In [35]:
# TODO: 다음 두 행렬의 행렬 곱을 계산하고, 각 원소의 계산 과정을 출력하세요
X = np.array([[2, 1],
              [3, 4]])
Y = np.array([[1, 0],
              [5, 2]])

# 여기에 코드 작성
print(X@Y)
print("-계산과정-")
print(X[0,:]@Y[:,0].T)
print(X[0,:]@Y[:,1].T)
print(X[1,:]@Y[:,0].T)
print(X[1,:]@Y[:,1].T)    

[[ 7  2]
 [23  8]]
-계산과정-
7
2
23
8


In [20]:
# 해답
X = np.array([[2, 1],
              [3, 4]])
Y = np.array([[1, 0],
              [5, 2]])

Z = X @ Y

print("행렬 X:")
print(X)
print()

print("행렬 Y:")
print(Y)
print()

print("X @ Y:")
print(Z)
print()

print("상세 계산 과정:")
print(f"Z[0,0] = X[0,:]·Y[:,0] = {X[0,0]}×{Y[0,0]} + {X[0,1]}×{Y[1,0]} = {X[0,0]*Y[0,0]} + {X[0,1]*Y[1,0]} = {Z[0,0]}")
print(f"Z[0,1] = X[0,:]·Y[:,1] = {X[0,0]}×{Y[0,1]} + {X[0,1]}×{Y[1,1]} = {X[0,0]*Y[0,1]} + {X[0,1]*Y[1,1]} = {Z[0,1]}")
print(f"Z[1,0] = X[1,:]·Y[:,0] = {X[1,0]}×{Y[0,0]} + {X[1,1]}×{Y[1,0]} = {X[1,0]*Y[0,0]} + {X[1,1]*Y[1,0]} = {Z[1,0]}")
print(f"Z[1,1] = X[1,:]·Y[:,1] = {X[1,0]}×{Y[0,1]} + {X[1,1]}×{Y[1,1]} = {X[1,0]*Y[0,1]} + {X[1,1]*Y[1,1]} = {Z[1,1]}")

행렬 X:
[[2 1]
 [3 4]]

행렬 Y:
[[1 0]
 [5 2]]

X @ Y:
[[ 7  2]
 [23  8]]

상세 계산 과정:
Z[0,0] = X[0,:]·Y[:,0] = 2×1 + 1×5 = 2 + 5 = 7
Z[0,1] = X[0,:]·Y[:,1] = 2×0 + 1×2 = 0 + 2 = 2
Z[1,0] = X[1,:]·Y[:,0] = 3×1 + 4×5 = 3 + 20 = 23
Z[1,1] = X[1,:]·Y[:,1] = 3×0 + 4×2 = 0 + 8 = 8


## 📝 복습 및 팁

### 핵심 정리
1. **벡터와 행렬 표기**
   - 1차원 배열 (3,) → 벡터
   - 2차원 배열 (3,3) → 3×3 행렬

2. **배열 vs 리스트**
   - `np.array([1,2,3]) + 1` ✅ 가능
   - `[1,2,3] + 1` ❌ 에러

3. **자료형**
   - NumPy 배열은 하나의 자료형만 가짐
   - 실수와 정수를 섞으면 자동으로 실수형으로 변환

4. **벡터화 연산**
   - for문 없이도 배열 연산을 효율적으로 수행 가능
   - 이는 딥러닝에서 **텐서(tensor)**를 다루는 기초가 됨

### 다음 학습 준비
- 오늘 배운 배열 조작과 기본 연산에 충분히 익숙해지세요
- 2일차에는 reshape, transpose 등 차원 조작을 배웁니다

## 🎯 추가 실습 문제

스스로 풀어보세요!

In [31]:
# 1. 5×5 영행렬을 만들고, 가운데 3×3 영역을 1로 채우세요
# 힌트: 슬라이싱 사용
zero_=np.zeros([5,5])
zero_[1:4,1:4]=1
print(zero_)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [32]:
# 2. 1부터 12까지의 정수로 3×4 행렬을 만드세요
# 힌트: np.arange와 reshape (2일차 내용 예습)
array=np.arange(1,13).reshape(3,4)
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
# 3. 두 벡터의 내적(dot product)을 계산하세요
# v1 = [1, 2, 3], v2 = [4, 5, 6]
# 결과: 1*4 + 2*5 + 3*6 = 4 + 10 + 18 = 32
# 힌트: np.dot() 또는 @ 연산자 사용
v1=np.array([1,2,3])
v2=np.array([4,5,6])
print(np.dot(v1,v2.T))

32
