# 2일차: 차원 조작 (Reshape, Transpose 등)과 배열 재구성

## 학습 목표
- 다차원 배열의 형태를 바꾸고 조작하는 방법 학습
- reshape, transpose, squeeze, concatenate 등의 사용법 익히기
- 배치(batch) 차원이나 채널(channel) 차원 등 딥러닝에서 자주 접하는 차원 개념 이해

In [49]:
import numpy as np
print(f"NumPy 버전: {np.__version__}")

NumPy 버전: 2.2.6


## 💡 이론 개요

### 차원 조작이란?
배열에 담긴 **데이터의 순서는 유지**하면서 **모양(차원)을 바꾸는** 것을 의미합니다.

### 주요 개념
- **Reshape**: 배열의 shape을 변경 (데이터 순서 유지)
- **Transpose**: 행과 열을 바꿈
- **Expand/Squeeze**: 차원 추가/제거
- **Stack/Concatenate**: 배열 합치기

### 딥러닝에서의 차원
- 이미지: (배치, 채널, 높이, 너비) 또는 (배치, 높이, 너비, 채널)
- 일반 데이터: (배치, 특성)

## 📚 1. Reshape - 배열 형태 변경

### 1.1 기본 reshape

In [50]:
# 1차원 배열 생성
arr = np.arange(12)  # 0부터 11까지
print("원본 배열:")
print(arr)
print(f"Shape: {arr.shape}")
print()

원본 배열:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)



In [51]:
# 3x4 행렬로 reshape
reshaped_3x4 = arr.reshape(3, 4)
print("3x4로 reshape:")
print(reshaped_3x4)
print(f"Shape: {reshaped_3x4.shape}")
print()

# 데이터는 행 기준(row-major)으로 채워집니다
# [0, 1, 2, 3]     ← 첫 번째 행
# [4, 5, 6, 7]     ← 두 번째 행
# [8, 9, 10, 11]   ← 세 번째 행

3x4로 reshape:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape: (3, 4)



In [52]:
# 2x6 행렬로 reshape
reshaped_2x6 = arr.reshape(2, 6)
print("2x6로 reshape:")
print(reshaped_2x6)
print(f"Shape: {reshaped_2x6.shape}")
print()

2x6로 reshape:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Shape: (2, 6)



In [53]:
# 3차원 배열로 reshape
reshaped_3d = arr.reshape(2, 2, 3)
print("2x2x3 3차원 배열로 reshape:")
print(reshaped_3d)
print(f"Shape: {reshaped_3d.shape}")
print()

print("해석: 2개의 (2x3) 행렬")
print("첫 번째 2x3:")
print(reshaped_3d[0])
print("\n두 번째 2x3:")
print(reshaped_3d[1])

2x2x3 3차원 배열로 reshape:
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Shape: (2, 2, 3)

해석: 2개의 (2x3) 행렬
첫 번째 2x3:
[[0 1 2]
 [3 4 5]]

두 번째 2x3:
[[ 6  7  8]
 [ 9 10 11]]


### 1.2 -1을 이용한 자동 계산

In [54]:
# -1을 사용하면 남은 차원을 자동으로 계산
arr = np.arange(24)

# 4행으로 하고 열은 자동 계산
auto_reshape = arr.reshape(4, -1)
print("reshape(4, -1):")
print(auto_reshape)
print(f"Shape: {auto_reshape.shape}  # 24 ÷ 4 = 6 (자동계산)")
print()

reshape(4, -1):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Shape: (4, 6)  # 24 ÷ 4 = 6 (자동계산)



In [55]:
# 3차원에서도 사용 가능
auto_3d = arr.reshape(2, 3, -1)
print("reshape(2, 3, -1):")
print(auto_3d)
print(f"Shape: {auto_3d.shape}  # 24 ÷ (2×3) = 4 (자동계산)")
print()

# -1로 1차원으로 펴기 (flatten과 유사)
flattened = arr.reshape(-1)
print("reshape(-1): 1차원으로 펴기")
print(flattened)
print(f"Shape: {flattened.shape}")

reshape(2, 3, -1):
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Shape: (2, 3, 4)  # 24 ÷ (2×3) = 4 (자동계산)

reshape(-1): 1차원으로 펴기
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Shape: (24,)


### 💬 Reshape 주의사항
- reshape 결과는 원본 배열과 메모리를 공유할 수 있음 (view)
- 원본 변경 시 reshape된 배열도 영향을 받을 수 있음
- 독립적인 복사가 필요하면 `.copy()` 사용

In [56]:
# View vs Copy 예제
original = np.arange(6)
view = original.reshape(2, 3)  # view (메모리 공유)
copy = original.reshape(2, 3).copy()  # 독립적 복사

print("원본:", original)
print("View:", view)
print("Copy:", copy)
print()

# 원본 수정
original[0] = 999

print("원본 수정 후:")
print("원본:", original)
print("View:", view, " ← 변경됨!")
print("Copy:", copy, " ← 변경 안됨")

원본: [0 1 2 3 4 5]
View: [[0 1 2]
 [3 4 5]]
Copy: [[0 1 2]
 [3 4 5]]

원본 수정 후:
원본: [999   1   2   3   4   5]
View: [[999   1   2]
 [  3   4   5]]  ← 변경됨!
Copy: [[0 1 2]
 [3 4 5]]  ← 변경 안됨


## 📚 2. Transpose - 전치

### 2.1 2차원 배열의 전치

In [57]:
# 2x3 행렬 생성
M = np.array([[1, 2, 3],
              [4, 5, 6]])

print("원본 행렬 (2x3):")
print(M)
print(f"Shape: {M.shape}")
print()

원본 행렬 (2x3):
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)



In [58]:
# 전치 (행과 열 바꾸기)
M_T = M.T  # 또는 np.transpose(M)

print("전치 행렬 (3x2):")
print(M_T)
print(f"Shape: {M_T.shape}")
print()

print("전치 과정:")
print("M[0,0]=1 → M_T[0,0]=1")
print("M[0,1]=2 → M_T[1,0]=2")
print("M[0,2]=3 → M_T[2,0]=3")
print("M[1,0]=4 → M_T[0,1]=4")
print("M[1,1]=5 → M_T[1,1]=5")
print("M[1,2]=6 → M_T[2,1]=6")

전치 행렬 (3x2):
[[1 4]
 [2 5]
 [3 6]]
Shape: (3, 2)

전치 과정:
M[0,0]=1 → M_T[0,0]=1
M[0,1]=2 → M_T[1,0]=2
M[0,2]=3 → M_T[2,0]=3
M[1,0]=4 → M_T[0,1]=4
M[1,1]=5 → M_T[1,1]=5
M[1,2]=6 → M_T[2,1]=6


### 2.2 다차원 배열의 축 교환

In [59]:
# 3차원 배열 생성 (배치, 높이, 너비)
arr_3d = np.arange(24).reshape(2, 3, 4)
print("원본 3D 배열 (2, 3, 4):")
print(arr_3d)
print(f"Shape: {arr_3d.shape}")
print()

원본 3D 배열 (2, 3, 4):
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Shape: (2, 3, 4)



In [60]:
# 축 순서 변경: (0, 1, 2) → (2, 0, 1)
transposed = arr_3d.transpose(2, 0, 1)
print("transpose(2, 0, 1) → Shape (4, 2, 3):")
print(transposed)
print(f"Shape: {transposed.shape}")
print()

# 축 설명:
# 원본: axis 0=2, axis 1=3, axis 2=4
# 결과: axis 0=4(원래 2), axis 1=2(원래 0), axis 2=3(원래 1)

transpose(2, 0, 1) → Shape (4, 2, 3):
[[[ 0  4  8]
  [12 16 20]]

 [[ 1  5  9]
  [13 17 21]]

 [[ 2  6 10]
  [14 18 22]]

 [[ 3  7 11]
  [15 19 23]]]
Shape: (4, 2, 3)



In [61]:
# 이미지 데이터 차원 변경 예제
# (높이, 너비, 채널) → (채널, 높이, 너비)
image_hwc = np.random.rand(28, 28, 3)  # 28x28 RGB 이미지
print(f"HWC 형식: {image_hwc.shape}  # (높이, 너비, 채널)")

image_chw = image_hwc.transpose(2, 0, 1)
print(f"CHW 형식: {image_chw.shape}  # (채널, 높이, 너비)")
print("※ PyTorch는 CHW 형식을 선호합니다")

HWC 형식: (28, 28, 3)  # (높이, 너비, 채널)
CHW 형식: (3, 28, 28)  # (채널, 높이, 너비)
※ PyTorch는 CHW 형식을 선호합니다


## 📚 3. 차원 추가/제거 (Expand_dims, Squeeze)

### 3.1 차원 추가 (expand_dims)

In [62]:
# 1차원 벡터
v = np.array([1, 2, 3, 4])
print("원본 벡터:")
print(v)
print(f"Shape: {v.shape}")
print()

원본 벡터:
[1 2 3 4]
Shape: (4,)



In [63]:
# axis=0에 차원 추가 (배치 차원)
v_batch = np.expand_dims(v, axis=0)
print("expand_dims(v, axis=0):")
print(v_batch)
print(f"Shape: {v_batch.shape}  # (1, 4) - 1개 샘플, 4개 특성")
print()

expand_dims(v, axis=0):
[[1 2 3 4]]
Shape: (1, 4)  # (1, 4) - 1개 샘플, 4개 특성



In [64]:
# axis=1에 차원 추가
v_column = np.expand_dims(v, axis=1)
print("expand_dims(v, axis=1):")
print(v_column)
print(f"Shape: {v_column.shape}  # (4, 1) - 열벡터")
print()

expand_dims(v, axis=1):
[[1]
 [2]
 [3]
 [4]]
Shape: (4, 1)  # (4, 1) - 열벡터



In [65]:
# axis=-1에 차원 추가 (맨 끝)
v_end = np.expand_dims(v, axis=-1)
print("expand_dims(v, axis=-1):")
print(v_end)
print(f"Shape: {v_end.shape}  # (4, 1)")
print()

# 실용 예: 흑백 이미지에 채널 차원 추가
grayscale = np.random.rand(28, 28)  # 28x28 흑백
print(f"흑백 이미지: {grayscale.shape}")

grayscale_with_channel = np.expand_dims(grayscale, axis=-1)
print(f"채널 추가: {grayscale_with_channel.shape}  # (28, 28, 1)")

expand_dims(v, axis=-1):
[[1]
 [2]
 [3]
 [4]]
Shape: (4, 1)  # (4, 1)

흑백 이미지: (28, 28)
채널 추가: (28, 28, 1)  # (28, 28, 1)


### 3.2 차원 제거 (squeeze)

In [66]:
# 크기 1인 차원을 가진 배열
arr = np.array([[[1, 2, 3]]])  # shape: (1, 1, 3)
print("원본 배열:")
print(arr)
print(f"Shape: {arr.shape}")
print()

원본 배열:
[[[1 2 3]]]
Shape: (1, 1, 3)



In [67]:
# 모든 크기 1 차원 제거
squeezed = np.squeeze(arr)
print("squeeze(arr):")
print(squeezed)
print(f"Shape: {squeezed.shape}  # (3,) - 크기 1인 차원들이 제거됨")
print()

squeeze(arr):
[1 2 3]
Shape: (3,)  # (3,) - 크기 1인 차원들이 제거됨



In [88]:
# 특정 axis만 제거
arr2 = np.array([[[1, 2, 3], [4, 5, 6]]])  # shape: (1, 2, 3)
print(f"원본: {arr2.shape}")

squeezed_axis0 = np.squeeze(arr2)
print(f"squeeze(axis=0): {squeezed_axis0.shape}  # (2, 3)")
print(squeezed_axis0)

원본: (1, 2, 3)
squeeze(axis=0): (2, 3)  # (2, 3)
[[1 2 3]
 [4 5 6]]


## 📚 4. 배열 연결 (Concatenate, Stack)

### 4.1 Concatenate - 기존 차원으로 연결

In [2]:
# 1차원 배열 연결
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

concat = np.concatenate((a, b) )
print(f"{a.shape}\n")
print(b.shape)
print("1D 배열 concatenate:")
print(f"a = {a}")
print(f"b = {b}")
print(f"concatenate([a, b]) = {concat}")
print(f"Shape: {concat.shape}")
print()

(3,)

(3,)
1D 배열 concatenate:
a = [1 2 3]
b = [4 5 6]
concatenate([a, b]) = [1 2 3 4 5 6]
Shape: (6,)



In [70]:
# 2차원 배열 연결 - axis=0 (행 방향)
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

concat_axis0 = np.concatenate([A, B], axis=0)
print("2D 배열 concatenate (axis=0, 행 방향):")
print(concat_axis0)
print(f"Shape: {concat_axis0.shape}  # (4, 2)")
print()

2D 배열 concatenate (axis=0, 행 방향):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Shape: (4, 2)  # (4, 2)



In [71]:
# 2차원 배열 연결 - axis=1 (열 방향)
concat_axis1 = np.concatenate([A, B], axis=1)
print("2D 배열 concatenate (axis=1, 열 방향):")
print(concat_axis1)
print(f"Shape: {concat_axis1.shape}  # (2, 4)")
print()

2D 배열 concatenate (axis=1, 열 방향):
[[1 2 5 6]
 [3 4 7 8]]
Shape: (2, 4)  # (2, 4)



### 4.2 Stack - 새로운 차원으로 쌓기

In [72]:
# 1차원 배열 stack
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

stacked = np.stack((a, b))
print("1D 배열 stack (axis=0):")
print(stacked)
print(f"Shape: {stacked.shape}  # (2, 3) - 새로운 차원 생성!")
print()

# concatenate와 비교
print("비교:")
print(f"concatenate: {np.concatenate([a, b]).shape}  # (6,)")
print(f"stack:       {stacked.shape}  # (2, 3)")

1D 배열 stack (axis=0):
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)  # (2, 3) - 새로운 차원 생성!

비교:
concatenate: (6,)  # (6,)
stack:       (2, 3)  # (2, 3)


In [73]:
# stack axis 변경
stacked_axis1 = np.stack([a, b], axis=1)
print("stack (axis=1):")
print(stacked_axis1)
print(f"Shape: {stacked_axis1.shape}  # (3, 2)")
print()

stack (axis=1):
[[1 4]
 [2 5]
 [3 6]]
Shape: (3, 2)  # (3, 2)



In [74]:
# 이미지 배치 만들기 예제
img1 = np.random.rand(28, 28)  # 이미지 1
img2 = np.random.rand(28, 28)  # 이미지 2
img3 = np.random.rand(28, 28)  # 이미지 3

# 배치로 쌓기
batch = np.stack([img1, img2, img3], axis=0)
print("이미지 배치:")
print(f"개별 이미지: {img1.shape}")
print(f"배치: {batch.shape}  # (3, 28, 28) - 3장의 28x28 이미지")

이미지 배치:
개별 이미지: (28, 28)
배치: (3, 28, 28)  # (3, 28, 28) - 3장의 28x28 이미지


## 🔥 연습 문제

### 문제 1: Reshape 연습

In [103]:
# TODO: 0부터 15까지의 정수 배열을 만들고
# 1. 4x4 행렬로 reshape
# 2. 2x2x4 3차원 배열로 reshape
# 3. reshape(-1)로 다시 1차원으로

# 여기에 코드 작성
a=np.arange(16)
a=a.reshape(4,4)
print(a)
a=a.reshape(2,2,4)
print(a)
a=a.reshape(-1)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [76]:
# 해답
arr = np.arange(16)
print("원본 배열:")
print(arr)
print(f"Shape: {arr.shape}")
print()

# 1. 4x4 행렬
arr_4x4 = arr.reshape(4, 4)
print("4x4 행렬:")
print(arr_4x4)
print(f"Shape: {arr_4x4.shape}")
print()

# 2. 2x2x4 3차원
arr_3d = arr.reshape(2, 2, 4)
print("2x2x4 3차원 배열:")
print(arr_3d)
print(f"Shape: {arr_3d.shape}")
print()

# 3. 다시 1차원으로
arr_1d = arr_3d.reshape(-1)
print("1차원으로:")
print(arr_1d)
print(f"Shape: {arr_1d.shape}")

원본 배열:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Shape: (16,)

4x4 행렬:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Shape: (4, 4)

2x2x4 3차원 배열:
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
Shape: (2, 2, 4)

1차원으로:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Shape: (16,)


### 문제 2: Transpose 연습

In [104]:
# TODO: 2x3 행렬 M = [[1,2,3],[4,5,6]]를 전치하세요
# 결과가 3x2 행렬인지 확인하세요

# 여기에 코드 작성
M=np.array([[1,2,3],[4,5,6]])
print(M.T)

[[1 4]
 [2 5]
 [3 6]]


In [78]:
# 해답
M = np.array([[1, 2, 3],
              [4, 5, 6]])

print("원본 (2x3):")
print(M)
print(f"Shape: {M.shape}")
print()

M_T = M.T
print("전치 (3x2):")
print(M_T)
print(f"Shape: {M_T.shape}")
print()

print("확인: M[i,j] == M_T[j,i]")
print(f"M[0,2] = {M[0,2]}, M_T[2,0] = {M_T[2,0]}")
print(f"M[1,1] = {M[1,1]}, M_T[1,1] = {M_T[1,1]}")

원본 (2x3):
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

전치 (3x2):
[[1 4]
 [2 5]
 [3 6]]
Shape: (3, 2)

확인: M[i,j] == M_T[j,i]
M[0,2] = 3, M_T[2,0] = 3
M[1,1] = 5, M_T[1,1] = 5


### 문제 3: 차원 추가/제거

In [105]:
# TODO: 1차원 배열 v = [7, 8, 9]에
# 1. expand_dims로 axis=0에 차원 추가
# 2. squeeze로 다시 원래대로

# 여기에 코드 작성
M=np.array([7,8,9])
M=np.expand_dims(M,axis=0)
print(M.shape)
print(M)


(1, 3)
[[7 8 9]]


In [80]:
# 해답
v = np.array([7, 8, 9])

print("원본:")
print(v)
print(f"Shape: {v.shape}")
print()

# 차원 추가
v_expanded = np.expand_dims(v, axis=0)
print("expand_dims(axis=0):")
print(v_expanded)
print(f"Shape: {v_expanded.shape}")
print()

# 차원 제거
v_squeezed = np.squeeze(v_expanded)
print("squeeze:")
print(v_squeezed)
print(f"Shape: {v_squeezed.shape}")
print()

print(f"원본과 동일: {np.array_equal(v, v_squeezed)}")

원본:
[7 8 9]
Shape: (3,)

expand_dims(axis=0):
[[7 8 9]]
Shape: (1, 3)

squeeze:
[7 8 9]
Shape: (3,)

원본과 동일: True


### 문제 4: 연결과 스택

In [110]:
# TODO: a = [1,2,3], b = [4,5,6] 두 벡터에 대해
# 1. concatenate 결과와 shape 확인
# 2. stack 결과와 shape 확인
# 3. 차이점 설명

# 여기에 코드 작성
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate([a,b])
d=np.stack([a,b])
print(f"{c}/n")
print(d)

[1 2 3 4 5 6]/n
[[1 2 3]
 [4 5 6]]


In [82]:
# 해답
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("벡터 a:", a)
print("벡터 b:", b)
print()

# 1. Concatenate
concat_result = np.concatenate([a, b])
print("concatenate([a, b]):")
print(concat_result)
print(f"Shape: {concat_result.shape}")
print("설명: 같은 차원에서 이어붙임")
print()

# 2. Stack
stack_result = np.stack([a, b])
print("stack([a, b]):")
print(stack_result)
print(f"Shape: {stack_result.shape}")
print("설명: 새로운 차원을 만들어 쌓음")
print()

# 3. 차이점
print("차이점 정리:")
print(f"concatenate: (3,) + (3,) → (6,)   # 1차원 유지")
print(f"stack:       (3,) + (3,) → (2,3)  # 2차원으로 증가")

벡터 a: [1 2 3]
벡터 b: [4 5 6]

concatenate([a, b]):
[1 2 3 4 5 6]
Shape: (6,)
설명: 같은 차원에서 이어붙임

stack([a, b]):
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
설명: 새로운 차원을 만들어 쌓음

차이점 정리:
concatenate: (3,) + (3,) → (6,)   # 1차원 유지
stack:       (3,) + (3,) → (2,3)  # 2차원으로 증가


## 📝 복습 및 팁

### 핵심 정리

| 연산 | 기능 | 차원 변화 | 예시 |
|------|------|----------|------|
| `reshape` | 형태 변경 | 유지 가능 | (12,) → (3,4) |
| `transpose` | 축 교환 | 유지 | (2,3) → (3,2) |
| `expand_dims` | 차원 추가 | +1 | (3,) → (1,3) |
| `squeeze` | 차원 제거 | -n | (1,3,1) → (3,) |
| `concatenate` | 이어붙이기 | 유지 | (3,)+(3,) → (6,) |
| `stack` | 쌓기 | +1 | (3,)+(3,) → (2,3) |

### 실전 팁
1. **-1 활용**: reshape에서 한 차원은 자동 계산 가능
2. **메모리 공유**: reshape/transpose는 view일 수 있음
3. **배치 차원**: 딥러닝에서는 첫 차원이 보통 배치
4. **차원 확인**: 연산 전후 항상 shape 확인 습관화

### 딥러닝 활용
- 이미지 형식 변환 (HWC ↔ CHW)
- 배치 구성 (stack으로 여러 샘플 합치기)
- 차원 맞추기 (expand_dims로 배치/채널 추가)

## 🎯 추가 실습 문제

In [83]:
# 1. 6개 원소를 가진 배열을 만들고, 가능한 모든 형태로 reshape 해보세요
# 힌트: (6,), (1,6), (6,1), (2,3), (3,2), (1,2,3), ...


In [84]:
# 2. 10개의 28x28 흑백 이미지를 배치로 만들고,
#    각 이미지에 채널 차원을 추가하세요
# 최종 shape: (10, 28, 28, 1)


In [85]:
# 3. (5, 4) 행렬 3개를 만들어서
#    a) concatenate로 (15, 4) 만들기
#    b) stack으로 (3, 5, 4) 만들기
