# 3일차: 텐서 연산 (행렬 곱셈, 브로드캐스팅, 합치기 등)

## 학습 목표
- **행렬 곱셈(matmul)**과 브로드캐스팅(broadcasting) 개념 이해
- 원소별 연산과 행렬 연산의 차이 구분
- 텐서 간의 다양한 연산 실습
- 집계 연산 및 비교 연산 학습

In [1]:
import numpy as np
print(f"NumPy 버전: {np.__version__}")

NumPy 버전: 2.2.6


## 💡 이론 개요

### 행렬 곱셈 (Matrix Multiplication)
선형대수의 핵심 연산으로, (m×n) 행렬과 (n×p) 행렬을 곱하면 (m×p) 행렬이 됩니다.

**규칙**: i행 j열의 결과는 첫 번째 행렬의 i행과 두 번째 행렬의 j열의 **내적(dot product)**

### 브로드캐스팅 (Broadcasting)
배열(텐서) 간 크기가 달라도 자동으로 크기를 맞춰서 원소별 연산을 수행하게 해주는 기능

**규칙**: 오른쪽 끝 차원부터 비교하여, 차원 크기가 일치하거나 둘 중 하나가 1이면 호환 가능

## 📚 1. 행렬 곱셈 (Matmul)

### 1.1 벡터 내적 (Dot Product)

In [2]:
# 두 벡터의 내적
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 방법 1: np.dot()
dot_result = np.dot(a, b)
print("벡터 내적 (np.dot):")
print(f"a = {a}")
print(f"b = {b}")
print(f"a·b = {dot_result}")
print()

# 계산 과정
print("계산 과정:")
print(f"1×4 + 2×5 + 3×6 = {1*4} + {2*5} + {3*6} = {dot_result}")
print()

# 방법 2: @ 연산자
dot_result2 = a @ b
print(f"a @ b = {dot_result2}  (동일한 결과)")

벡터 내적 (np.dot):
a = [1 2 3]
b = [4 5 6]
a·b = 32

계산 과정:
1×4 + 2×5 + 3×6 = 4 + 10 + 18 = 32

a @ b = 32  (동일한 결과)


### 1.2 행렬-벡터 곱셈

In [3]:
# 행렬 × 벡터
A = np.array([[1, 2, 3],
              [4, 5, 6]])
v = np.array([1, 0, -1])

result = A @ v
print("행렬-벡터 곱셈:")
print(f"A (2×3):")
print(A)
print(f"\nv (3,):")
print(v)
print(f"\nA @ v (2,):")
print(result)
print()

print("계산 과정:")
print(f"result[0] = A[0,:]·v = [1,2,3]·[1,0,-1] = 1×1 + 2×0 + 3×(-1) = {result[0]}")
print(f"result[1] = A[1,:]·v = [4,5,6]·[1,0,-1] = 4×1 + 5×0 + 6×(-1) = {result[1]}")

행렬-벡터 곱셈:
A (2×3):
[[1 2 3]
 [4 5 6]]

v (3,):
[ 1  0 -1]

A @ v (2,):
[-2 -2]

계산 과정:
result[0] = A[0,:]·v = [1,2,3]·[1,0,-1] = 1×1 + 2×0 + 3×(-1) = -2
result[1] = A[1,:]·v = [4,5,6]·[1,0,-1] = 4×1 + 5×0 + 6×(-1) = -2


### 1.3 행렬-행렬 곱셈

In [4]:
# 2×3 행렬 × 3×2 행렬 = 2×2 행렬
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

C = A @ B

print("행렬-행렬 곱셈:")
print(f"A (2×3):")
print(A)
print(f"\nB (3×2):")
print(B)
print(f"\nC = A @ B (2×2):")
print(C)
print()

print("상세 계산 과정:")
print("C[0,0] = A[0파,:]·B[:,0] = [1,2,3]·[7,9,11]")
print(f"       = 1×7 + 2×9 + 3×11 = {1*7} + {2*9} + {3*11} = {C[0,0]}")
print()
print("C[0,1] = A[0,:]·B[:,1] = [1,2,3]·[8,10,12]")
print(f"       = 1×8 + 2×10 + 3×12 = {1*8} + {2*10} + {3*12} = {C[0,1]}")
print()
print("C[1,0] = A[1,:]·B[:,0] = [4,5,6]·[7,9,11]")
print(f"       = 4×7 + 5×9 + 6×11 = {4*7} + {5*9} + {6*11} = {C[1,0]}")
print()
print("C[1,1] = A[1,:]·B[:,1] = [4,5,6]·[8,10,12]")
print(f"       = 4×8 + 5×10 + 6×12 = {4*8} + {5*10} + {6*12} = {C[1,1]}")

행렬-행렬 곱셈:
A (2×3):
[[1 2 3]
 [4 5 6]]

B (3×2):
[[ 7  8]
 [ 9 10]
 [11 12]]

C = A @ B (2×2):
[[ 58  64]
 [139 154]]

상세 계산 과정:
C[0,0] = A[0파,:]·B[:,0] = [1,2,3]·[7,9,11]
       = 1×7 + 2×9 + 3×11 = 7 + 18 + 33 = 58

C[0,1] = A[0,:]·B[:,1] = [1,2,3]·[8,10,12]
       = 1×8 + 2×10 + 3×12 = 8 + 20 + 36 = 64

C[1,0] = A[1,:]·B[:,0] = [4,5,6]·[7,9,11]
       = 4×7 + 5×9 + 6×11 = 28 + 45 + 66 = 139

C[1,1] = A[1,:]·B[:,1] = [4,5,6]·[8,10,12]
       = 4×8 + 5×10 + 6×12 = 32 + 50 + 72 = 154


### 💬 원소별 곱 vs 행렬 곱

In [5]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print("행렬 A:")
print(A)
print("\n행렬 B:")
print(B)
print()

# 원소별 곱 (Hadamard product)
element_wise = A * B
print("원소별 곱 (A * B):")
print(element_wise)
print("설명: 같은 위치의 원소끼리 곱함")
print(f"[[1×5, 2×6], [3×7, 4×8]] = [[{1*5}, {2*6}], [{3*7}, {4*8}]]")
print()

# 행렬 곱
matrix_mult = A @ B
print("행렬 곱 (A @ B):")
print(matrix_mult)
print("설명: 행과 열의 내적")
print(f"[[1×5+2×7, 1×6+2×8], [3×5+4×7, 3×6+4×8]]")
print(f"= [[{1*5+2*7}, {1*6+2*8}], [{3*5+4*7}, {3*6+4*8}]]")

행렬 A:
[[1 2]
 [3 4]]

행렬 B:
[[5 6]
 [7 8]]

원소별 곱 (A * B):
[[ 5 12]
 [21 32]]
설명: 같은 위치의 원소끼리 곱함
[[1×5, 2×6], [3×7, 4×8]] = [[5, 12], [21, 32]]

행렬 곱 (A @ B):
[[19 22]
 [43 50]]
설명: 행과 열의 내적
[[1×5+2×7, 1×6+2×8], [3×5+4×7, 3×6+4×8]]
= [[19, 22], [43, 50]]


## 📚 2. 브로드캐스팅 (Broadcasting)

### 2.1 스칼라 브로드캐스팅

In [6]:
# 배열 + 스칼라
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("원본 배열:")
print(arr)
print()

# 스칼라 더하기
result = arr + 10
print("배열 + 10:")
print(result)
print("설명: 10이 모든 원소에 더해짐")
print()

# 스칼라 곱하기
result2 = arr * 2
print("배열 × 2:")
print(result2)
print("설명: 모든 원소가 2배가 됨")

원본 배열:
[[1 2 3]
 [4 5 6]]

배열 + 10:
[[11 12 13]
 [14 15 16]]
설명: 10이 모든 원소에 더해짐

배열 × 2:
[[ 2  4  6]
 [ 8 10 12]]
설명: 모든 원소가 2배가 됨


### 2.2 1차원 배열 브로드캐스팅

In [7]:
# 2D 배열 + 1D 배열
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
v = np.array([10, 20, 30])

print("행렬 M (3×3):")
print(M)
print(f"Shape: {M.shape}")
print()

print("벡터 v (3,):")
print(v)
print(f"Shape: {v.shape}")
print()

result = M + v
print("M + v:")
print(result)
print()

print("브로드캐스팅 과정:")
print("v는 각 행에 반복 적용됨:")
print("[[1,2,3],   [[10,20,30],   [[11,22,33],")
print(" [4,5,6], +  [10,20,30], =  [14,25,36],")
print(" [7,8,9]]    [10,20,30]]    [17,28,39]]")

행렬 M (3×3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)

벡터 v (3,):
[10 20 30]
Shape: (3,)

M + v:
[[11 22 33]
 [14 25 36]
 [17 28 39]]

브로드캐스팅 과정:
v는 각 행에 반복 적용됨:
[[1,2,3],   [[10,20,30],   [[11,22,33],
 [4,5,6], +  [10,20,30], =  [14,25,36],
 [7,8,9]]    [10,20,30]]    [17,28,39]]


### 2.3 브로드캐스팅 규칙 상세

In [8]:
# 다양한 브로드캐스팅 예제
print("브로드캐스팅 가능한 경우들:\n")

# 예제 1: (3,4) + (4,)
a1 = np.ones((3, 4))
b1 = np.array([1, 2, 3, 4])
print(f"1. {a1.shape} + {b1.shape} = {(a1 + b1).shape} ✅")
print("   마지막 차원 4가 일치")
print()

# 예제 2: (3,1) + (3,)
a2 = np.ones((3, 1))
b2 = np.array([1, 2, 3])
print(f"2. {a2.shape} + {b2.shape} = {(a2 + b2).shape} ✅")
print("   (3,1)이 (3,3)으로 확장")
print()

# 예제 3: (1,3) + (3,1)
a3 = np.ones((1, 3))
b3 = np.ones((3, 1))
print(f"3. {a3.shape} + {b3.shape} = {(a3 + b3).shape} ✅")
print("   둘 다 (3,3)으로 확장")
print()

# 예제 4: (2,3,4) + (3,4)
a4 = np.ones((2, 3, 4))
b4 = np.ones((3, 4))
print(f"4. {a4.shape} + {b4.shape} = {(a4 + b4).shape} ✅")
print("   마지막 두 차원이 일치")

브로드캐스팅 가능한 경우들:

1. (3, 4) + (4,) = (3, 4) ✅
   마지막 차원 4가 일치

2. (3, 1) + (3,) = (3, 3) ✅
   (3,1)이 (3,3)으로 확장

3. (1, 3) + (3, 1) = (3, 3) ✅
   둘 다 (3,3)으로 확장

4. (2, 3, 4) + (3, 4) = (2, 3, 4) ✅
   마지막 두 차원이 일치


In [9]:
# 브로드캐스팅 불가능한 경우
print("브로드캐스팅 불가능한 경우:\n")

try:
    a = np.ones((3, 4))
    b = np.ones((3,))  # shape (3,)
    result = a + b
except ValueError as e:
    print(f"❌ {a.shape} + {b.shape}")
    print(f"   오류: 마지막 차원이 4 vs 3으로 불일치")
    print()

# 해결 방법: reshape로 차원 맞추기
b_reshaped = b.reshape(3, 1)
result = a + b_reshaped
print(f"✅ 해결: {a.shape} + {b_reshaped.shape} = {result.shape}")

브로드캐스팅 불가능한 경우:

❌ (3, 4) + (3,)
   오류: 마지막 차원이 4 vs 3으로 불일치

✅ 해결: (3, 4) + (3, 1) = (3, 4)


### 2.4 실용 예제: 정규화(Normalization)

In [10]:
# 각 샘플(행)을 평균 0, 표준편차 1로 정규화
data = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]], dtype=float)

print("원본 데이터:")
print(data)
print()

# 각 행의 평균과 표준편차
mean = data.mean(axis=1, keepdims=True)  # shape: (3, 1)
std = data.std(axis=1, keepdims=True)    # shape: (3, 1)

print(f"각 행의 평균 (shape {mean.shape}):")
print(mean)
print()

print(f"각 행의 표준편차 (shape {std.shape}):")
print(std)
print()

# 정규화: (x - mean) / std
normalized = (data - mean) / std
print("정규화된 데이터:")
print(normalized)
print()

# 검증: 각 행의 평균이 0에 가까운지 확인
print("정규화 후 각 행의 평균:")
print(normalized.mean(axis=1))  # 0에 매우 가까움
print("\n정규화 후 각 행의 표준편차:")
print(normalized.std(axis=1))   # 1에 매우 가까움

원본 데이터:
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]

각 행의 평균 (shape (3, 1)):
[[ 2.5]
 [ 6.5]
 [10.5]]

각 행의 표준편차 (shape (3, 1)):
[[1.11803399]
 [1.11803399]
 [1.11803399]]

정규화된 데이터:
[[-1.34164079 -0.4472136   0.4472136   1.34164079]
 [-1.34164079 -0.4472136   0.4472136   1.34164079]
 [-1.34164079 -0.4472136   0.4472136   1.34164079]]

정규화 후 각 행의 평균:
[0. 0. 0.]

정규화 후 각 행의 표준편차:
[1. 1. 1.]


## 📚 3. 집계 연산 (Aggregation)

### 3.1 기본 집계 함수

In [11]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("배열:")
print(arr)
print()

# 전체 집계
print("전체 집계:")
print(f"합계: {arr.sum()}")
print(f"평균: {arr.mean():.2f}")
print(f"최댓값: {arr.max()}")
print(f"최솟값: {arr.min()}")
print(f"표준편차: {arr.std():.2f}")
print()

배열:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

전체 집계:
합계: 45
평균: 5.00
최댓값: 9
최솟값: 1
표준편차: 2.58



### 3.2 axis를 따른 집계

In [12]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("배열:")
print(arr)
print()

# axis=0 (열 방향, 각 열의 집계)
print("axis=0 (열 방향):")
sum_axis0 = arr.sum(axis=0)
print(f"각 열의 합: {sum_axis0}")
print(f"계산: [1+4+7, 2+5+8, 3+6+9] = [{1+4+7}, {2+5+8}, {3+6+9}]")
print()

# axis=1 (행 방향, 각 행의 집계)
print("axis=1 (행 방향):")
sum_axis1 = arr.sum(axis=1)
print(f"각 행의 합: {sum_axis1}")
print(f"계산: [1+2+3, 4+5+6, 7+8+9] = [{1+2+3}, {4+5+6}, {7+8+9}]")
print()

# keepdims: 차원 유지
sum_keepdims = arr.sum(axis=1, keepdims=True)
print(f"keepdims=True: shape {sum_keepdims.shape}")
print(sum_keepdims)
print("※ 브로드캐스팅에 유용")

배열:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

axis=0 (열 방향):
각 열의 합: [12 15 18]
계산: [1+4+7, 2+5+8, 3+6+9] = [12, 15, 18]

axis=1 (행 방향):
각 행의 합: [ 6 15 24]
계산: [1+2+3, 4+5+6, 7+8+9] = [6, 15, 24]

keepdims=True: shape (3, 1)
[[ 6]
 [15]
 [24]]
※ 브로드캐스팅에 유용


### 3.3 argmax, argmin - 최대/최소 위치 찾기

In [13]:
arr = np.array([[3, 1, 4],
                [1, 5, 9],
                [2, 6, 5]])

print("배열:")
print(arr)
print()

# 전체에서 최댓값 인덱스
idx = arr.argmax()
print(f"최댓값 위치 (flatten): {idx}")
print(f"최댓값: {arr.flat[idx]}")
print()

# 각 행에서 최댓값 위치
idx_axis1 = arr.argmax(axis=1)
print(f"각 행에서 최댓값 위치: {idx_axis1}")
print("해석: 0행 → 인덱스 2 (값 4)")
print("     1행 → 인덱스 2 (값 9)")
print("     2행 → 인덱스 1 (값 6)")

배열:
[[3 1 4]
 [1 5 9]
 [2 6 5]]

최댓값 위치 (flatten): 5
최댓값: 9

각 행에서 최댓값 위치: [2 2 1]
해석: 0행 → 인덱스 2 (값 4)
     1행 → 인덱스 2 (값 9)
     2행 → 인덱스 1 (값 6)


## 📚 4. 비교 연산과 필터링

### 4.1 불리언 배열

In [14]:
arr = np.array([1, 5, 3, 8, 2, 7])

print("배열:", arr)
print()

# 비교 연산
mask = arr > 4
print("arr > 4:")
print(mask)
print(f"타입: {mask.dtype}")
print()

# 불리언 인덱싱으로 필터링
filtered = arr[mask]
print("4보다 큰 값들:")
print(filtered)
print()

# 한 줄로
print("한 줄로: arr[arr > 4] =", arr[arr > 4])

배열: [1 5 3 8 2 7]

arr > 4:
[False  True False  True False  True]
타입: bool

4보다 큰 값들:
[5 8 7]

한 줄로: arr[arr > 4] = [5 8 7]


In [15]:
# 여러 조건 조합
arr = np.array([1, 5, 3, 8, 2, 7, 4, 6])

print("배열:", arr)
print()

# AND 조건: &
print("3 < arr < 7:")
result = arr[(arr > 3) & (arr < 7)]
print(result)
print()

# OR 조건: |
print("arr < 3 또는 arr > 6:")
result2 = arr[(arr < 3) | (arr > 6)]
print(result2)

배열: [1 5 3 8 2 7 4 6]

3 < arr < 7:
[5 4 6]

arr < 3 또는 arr > 6:
[1 8 2 7]


### 4.2 np.where - 조건부 값 선택

In [16]:
arr = np.array([1, 2, 3, 4, 5, 6])

print("원본 배열:", arr)
print()

# np.where(조건, True일 때 값, False일 때 값)
result = np.where(arr > 3, arr, 0)
print("3보다 크면 그대로, 아니면 0:")
print(result)
print()

# 실용 예: ReLU 함수
x = np.array([-2, -1, 0, 1, 2])
relu = np.where(x > 0, x, 0)
print("ReLU 함수적용 (max(0, x)):")
print(f"입력: {x}")
print(f"출력: {relu}")

원본 배열: [1 2 3 4 5 6]

3보다 크면 그대로, 아니면 0:
[0 0 0 4 5 6]

ReLU 함수적용 (max(0, x)):
입력: [-2 -1  0  1  2]
출력: [0 0 0 1 2]


## 🔥 연습 문제

### 문제 1: 행렬 곱셈 이해

In [29]:
# TODO: 다음 두 행렬의 행렬 곱과 원소별 곱을 계산하고 차이를 설명하세요
A = np.array([[2, 1],
              [3, 4]])
B = np.array([[1, 0],
              [5, 2]])

# 여기에 코드 작성
print(A@B)
print(A*B)

[[ 7  2]
 [23  8]]
[[ 2  0]
 [15  8]]


In [18]:
# 해답
A = np.array([[2, 1],
              [3, 4]])
B = np.array([[1, 0],
              [5, 2]])

print("A:")
print(A)
print("\nB:")
print(B)
print()

# 원소별 곱
hadamard = A * B
print("원소별 곱 (A * B):")
print(hadamard)
print(f"[[2×1, 1×0], [3×5, 4×2]] = [[{2*1}, {1*0}], [{3*5}, {4*2}]]")
print()

# 행렬 곱
matmul = A @ B
print("행렬 곱 (A @ B):")
print(matmul)
print("상세 계산:")
print(f"[0,0]: 2×1 + 1×5 = {2*1+1*5}")
print(f"[0,1]: 2×0 + 1×2 = {2*0+1*2}")
print(f"[1,0]: 3×1 + 4×5 = {3*1+4*5}")
print(f"[1,1]: 3×0 + 4×2 = {3*0+4*2}")

A:
[[2 1]
 [3 4]]

B:
[[1 0]
 [5 2]]

원소별 곱 (A * B):
[[ 2  0]
 [15  8]]
[[2×1, 1×0], [3×5, 4×2]] = [[2, 0], [15, 8]]

행렬 곱 (A @ B):
[[ 7  2]
 [23  8]]
상세 계산:
[0,0]: 2×1 + 1×5 = 7
[0,1]: 2×0 + 1×2 = 2
[1,0]: 3×1 + 4×5 = 23
[1,1]: 3×0 + 4×2 = 8


### 문제 2: 브로드캐스팅 연습

In [39]:
# TODO: 3x4 행렬 M과 길이 4인 벡터 v를 만들어
# M의 각 행에 v를 더하세요 (브로드캐스팅 활용)

# 여기에 코드 작성
M=np.random.randint(1,10,size=(3,4))
v=np.random.randint(1,10,size=(4))
print(M)
print(f"{M.shape}\n")
print(v)
print(v.shape)
c=M+v
print(c.shape)

[[5 4 8 6]
 [2 4 4 6]
 [6 1 8 6]]
(3, 4)

[3 9 2 8]
(4,)
(3, 4)


In [20]:
# 해답
M = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
v = np.array([10, 20, 30, 40])

print("행렬 M (3×4):")
print(M)
print()

print("벡터 v (4,):")
print(v)
print()

result = M + v
print("M + v:")
print(result)
print()

print("브로드캐스팅:")
print("v가 각 행에 반복 적용됨")
print(f"shape: {M.shape} + {v.shape} → {result.shape}")

행렬 M (3×4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

벡터 v (4,):
[10 20 30 40]

M + v:
[[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]

브로드캐스팅:
v가 각 행에 반복 적용됨
shape: (3, 4) + (4,) → (3, 4)


### 문제 3: 집계 연산

In [46]:
#Todo: 100개의 랜덤 값 생성 후
# 1. 평균과 표준편차 계산
# 2. 0보다 큰 값의 비율 계산
import numpy as np
# 재현성을 위해
np.random.seed(42)
# 여기에 코드 작성
population=np.random.rand(100)
mean=population.mean()
std=population.std()
x=population[population>0]
ratio=len(x)/len(population)
print(population)
print(f"mean:{mean}\n std:{std}\n ratio:{ratio}")

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985
 0.83244264 0.21233911 0.18182497 0.18340451 0.30424224 0.52475643
 0.43194502 0.29122914 0.61185289 0.13949386 0.29214465 0.36636184
 0.45606998 0.78517596 0.19967378 0.51423444 0.59241457 0.04645041
 0.60754485 0.17052412 0.06505159 0.94888554 0.96563203 0.80839735
 0.30461377 0.09767211 0.68423303 0.44015249 0.12203823 0.49517691
 0.03438852 0.9093204  0.25877998 0.66252228 0.31171108 0.52006802
 0.54671028 0.18485446 0.96958463 0.77513282 0.93949894 0.89482735
 0.59789998 0.92187424 0.0884925  0.19598286 0.04522729 0.32533033
 0.38867729 0.27134903 0.82873751 0.35675333 0.28093451 0.54269608
 0.14092422 0.80219698 0.07455064 0.98688694 0.77224477 0.19871568
 0.00552212 0.81546143 0.70685734 0.72900717 0.77127035 0.07404465
 0.35846573 0.11586906 0.86310343 0.62329813 0.33089802 0.06355835
 0.31098232 0.32518332 0.72960618 0.63755747 0.88721274 0.4722

In [47]:
# 해답
import numpy as np
np.random.seed(42)
arr = np.random.randn(100)  # 표준정규분포

print("랜덤 배열 생성 (처음 10개):")
print(arr[:10])
print()

# 1. 평균과 표준편차
mean = arr.mean()
std = arr.std()
print(f"평균: {mean:.4f}")
print(f"표준편차: {std:.4f}")
print()

# 2. 0보다 큰 값의 비율
positive_ratio = (arr > 0).mean()
print(f"0보다 큰 값의 비율: {positive_ratio:.2%}")
print(f"개수: {(arr > 0).sum()}/100")
print()

print("※ True는 1로, False는 0으로 계산됨")

랜덤 배열 생성 (처음 10개):
[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337 -0.23413696
  1.57921282  0.76743473 -0.46947439  0.54256004]

평균: -0.1038
표준편차: 0.9036

0보다 큰 값의 비율: 46.00%
개수: 46/100

※ True는 1로, False는 0으로 계산됨


### 문제 4: 조건부 연산

In [49]:
# TODO: -10에서 10까지의 배열을 만들고
# np.where를 사용하여 음수는 -1, 0은 0, 양수는 1로 변환하세요
# (sign 함수 구현)

# 여기에 코드 작성
import numpy as np
ranint=np.random.randint(-10,10,size=10)
print(ranint)
sign=np.where(ranint>0,1,-1)
print(sign)

[ 6  9  1 -4 -9 -8  6 -6  6  6]
[ 1  1  1 -1 -1 -1  1 -1  1  1]


In [24]:
# 해답
arr = np.arange(-10, 11)

print("원본 배열:")
print(arr)
print()

# np.where 중첩 사용
sign = np.where(arr > 0, 1, np.where(arr < 0, -1, 0))

print("sign 함수 적용:")
print(sign)
print()

# 또는 np.sign() 내장 함수 사용
sign_builtin = np.sign(arr)
print("np.sign() 내장 함수:")
print(sign_builtin)
print()

print(f"결과 일치: {np.array_equal(sign, sign_builtin)}")

원본 배열:
[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9  10]

sign 함수 적용:
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1  0  1  1  1  1  1  1  1  1  1  1]

np.sign() 내장 함수:
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1  0  1  1  1  1  1  1  1  1  1  1]

결과 일치: True


## 📝 복습 및 팁

### 핵심 정리

#### 연산 종류
| 연산 | 기호/함수 | 차원 변화 | 용도 |
|------|----------|----------|------|
| 원소별 곱 | `*` | 유지 | Hadamard product |
| 행렬 곱 | `@`, `np.matmul` | (m,n)@(n,p)→(m,p) | 선형변환 |
| 내적 | `np.dot`, `@` | 벡터→스칼라 | 유사도 |
| 브로드캐스팅 | 자동 | 작은 쪽 확장 | 효율적 연산 |

#### 집계 연산
- `axis=None`: 전체 집계
- `axis=0`: 열 방향 (각 열의 집계)
- `axis=1`: 행 방향 (각 행의 집계)
- `keepdims=True`: 차원 유지 (브로드캐스팅에 유용)

### 실전 팁
1. **shape 확인**: 항상 연산 전후 shape 확인
2. **브로드캐스팅 주의**: 의도치 않은 확장 방지
3. **메모리 효율**: for문 대신 벡터화 연산
4. **딥러닝**: 배치 단위 연산에 활용

### 다음 학습
- 4일차: 역행렬, 행렬식, 랭크
- 선형대수 이론을 NumPy로 실습

## 🎯 추가 실습 문제

In [56]:
# 1. 배치 정규화 구현
# (배치크기, 특성) shape의 데이터에 대해
# 각 특성별로 평균 0, 표준편차 1로 정규화
import numpy as np
np.random.seed(42)
batch_data = np.random.randn(32, 10)  # 32개 샘플, 10개 특성
# TODO: 각 열(특성)에 대해 정규화
mean=batch_data.mean(axis=0)
std=batch_data.std(axis=0)
normalization=(batch_data-mean)/std
print(np.round(normalization,2))


[[ 0.67 -0.31  0.5   1.49 -0.1  -0.35  1.49  0.99 -0.7   0.43]
 [-0.38 -0.7   0.12 -1.75 -1.51 -0.7  -1.16  0.44 -1.35 -1.24]
 [ 1.72 -0.41 -0.04 -1.29 -0.39  0.03 -1.3   0.52 -0.9  -0.28]
 [-0.53  2.05 -0.12 -0.94  0.91 -1.41  0.09 -2.28 -1.98  0.14]
 [ 0.93  0.06 -0.22 -0.23 -1.28 -0.87 -0.59  1.33  0.51 -1.55]
 [ 0.48 -0.6  -0.74  0.63  1.11  0.91 -0.98 -0.3   0.49  0.81]
 [-0.39 -0.36 -1.14 -1.08  0.9   1.37 -0.19  1.27  0.53 -0.59]
 [ 0.52  1.68 -0.14  1.53 -2.36  0.79 -0.03 -0.29  0.13 -1.74]
 [-0.11  0.28  1.28 -0.44 -0.64 -0.64  0.82  0.46 -0.79  0.41]
 [ 0.23  1.01 -0.76 -0.26 -0.25 -1.67  0.18  0.38  0.   -0.23]
 [-1.41 -0.64 -0.43 -0.7  -0.03  0.34  1.81  0.28  0.38 -0.1 ]
 [-1.96 -0.18 -0.05  2.37 -0.06  0.23 -0.16 -1.33  1.69  0.61]
 [ 0.99 -1.22  1.21 -1.27  0.68  2.27 -1.13 -0.61  0.14 -0.46]
 [-1.56 -0.06 -1.1   0.5  -0.75  1.58 -0.92 -0.32  1.2  -1.09]
 [ 0.37  1.41 -1.61  0.23  0.37  0.75 -1.39 -1.51  0.77  0.22]
 [ 0.4   0.27 -0.74  0.27  0.41 -0.87  1.79  0.63 -1.77

In [61]:
# 2. 유클리드 거리 행렬 계산
# 5개 점의 (x,y) 좌표가 주어졌을 때
# 모든 점 쌍 간의 거리 행렬 계산

points = np.random.rand(5, 2)  # 5개 점, 2차원
# TODO: 5x5 거리 행렬 계산
# 거리[i,j] = sqrt((x_i-x_j)^2 + (y_i-y_j)^2)
mat=np.zeros((5,5))
for i in range(0,5):
    for j in range(0,5):
        dist=points[i]-points[j]
        mat[i,j]=np.sqrt(np.sum(dist**2))

mat=np.unique(mat)
print(mat)
     
print(mat.size)

[0.         0.10267954 0.15671304 0.20945358 0.35271859 0.37781634
 0.40023165 0.51880273 0.53391416 0.60169436 0.86923983]
11


In [63]:
# 3. Softmax 함수 구현
# softmax(x_i) = exp(x_i) / sum(exp(x_j))

logits = np.array([2.0, 1.0, 0.1])
# TODO: softmax 계산 (합이 1이 되어야 함)
row=np.exp(logits)
row_sum=np.sum(row)
softmax=row/row_sum
print(softmax)
print(np.sum(softmax))

[0.65900114 0.24243297 0.09856589]
1.0
