# 4일차: 선형대수 핵심 I - 역행렬, 행렬식, 랭크

## 학습 목표
- 역행렬(inverse) 계산과 개념 이해
- 행렬식(determinant) 이해
- 행렬의 랭크(rank) 이해
- 선형 방정식 시스템 풀이

In [1]:
import numpy as np
print(f'NumPy 버전: {np.__version__}')

NumPy 버전: 2.2.6


## 💡 이론 개요

### 역행렬 (Inverse Matrix)
정방행렬 A에 대해 A⁻¹는 A·A⁻¹ = I (단위행렬) 관계를 만족하는 행렬

**용도**: 선형방정식 Ax=b의 해를 x=A⁻¹b로 구함

**조건**: det(A) ≠ 0 (비특이행렬)

### 행렬식 (Determinant)
정방행렬에 대해 정의되는 스칼라 값

**의미**: 
- 기하학적: 변환의 부피 스케일
- 대수적: det(A)=0이면 역행렬 없음

### 랭크 (Rank)
행렬의 선형독립인 행(또는 열)의 최대 개수

**의미**: 행렬이 표현할 수 있는 벡터 공간의 차원

## 📚 1. 역행렬 계산

### 1.1 2×2 행렬의 역행렬

In [2]:
# 2×2 행렬의 역행렬
import numpy as np
A = np.array([[4, 7],
              [2, 6]])

print('행렬 A:')
print(A)
print()

# NumPy로 역행렬 계산
A_inv = np.linalg.inv(A)
print('역행렬 A⁻¹:')
print(A_inv)
print()

# 수동 계산 (2×2 공식)
# A⁻¹ = 1/det(A) * [[d, -b], [-c, a]]
det_A = 4*6 - 7*2
print(f'행렬식: det(A) = 4×6 - 7×2 = {det_A}')
print()

A_inv_manual = (1/det_A) * np.array([[6, -7], [-2, 4]])
print('수동 계산한 역행렬:')
print(A_inv_manual)
print()

print(f'NumPy 결과와 일치: {np.allclose(A_inv, A_inv_manual)}')

행렬 A:
[[4 7]
 [2 6]]

역행렬 A⁻¹:
[[ 0.6 -0.7]
 [-0.2  0.4]]

행렬식: det(A) = 4×6 - 7×2 = 10

수동 계산한 역행렬:
[[ 0.6 -0.7]
 [-0.2  0.4]]

NumPy 결과와 일치: True


In [3]:
# 역행렬 검증: A @ A⁻¹ = I
import numpy as np
identity = A @ A_inv
print('A @ A⁻¹:')
print(identity)
print()

# 단위행렬과 비교
I = np.eye(2)
print('단위행렬 I:')
print(I)
print()

print(f'단위행렬과 일치 (허용오차 고려): {np.allclose(identity, I)}')

A @ A⁻¹:
[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]

단위행렬 I:
[[1. 0.]
 [0. 1.]]

단위행렬과 일치 (허용오차 고려): True


### 1.2 3×3 행렬의 역행렬

In [4]:
# 3×3 행렬
B = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

print('행렬 B:')
print(B)
print()

# 역행렬 계산
B_inv = np.linalg.inv(B)
print('역행렬 B⁻¹:')
print(B_inv)
print()

# 검증
identity_3 = B @ B_inv
print('B @ B⁻¹:')
print(identity_3)
print()

# 실수 오차 확인
print(f'단위행렬과 일치 (허용오차): {np.allclose(identity_3, np.eye(3))}')
print(f'최대 오차: {np.max(np.abs(identity_3 - np.eye(3))):.2e}')

행렬 B:
[[1 2 3]
 [0 1 4]
 [5 6 0]]

역행렬 B⁻¹:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]

B @ B⁻¹:
[[ 1.00000000e+00 -2.66453526e-15  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -7.10542736e-15  1.00000000e+00]]

단위행렬과 일치 (허용오차): True
최대 오차: 7.11e-15


## 📚 2. 행렬식 (Determinant)

### 2.1 행렬식 계산

In [5]:
# 2×2 행렬의 행렬식
A = np.array([[3, 8],
              [4, 6]])

det_A = np.linalg.det(A)
print('행렬 A:')
print(A)
print()

print(f'det(A) = {det_A}')
print()

# 수동 계산
det_manual = 3*6 - 8*4
print(f'수동 계산: 3×6 - 8×4 = {det_manual}')
print(f'일치: {np.isclose(det_A, det_manual)}')

행렬 A:
[[3 8]
 [4 6]]

det(A) = -14.000000000000004

수동 계산: 3×6 - 8×4 = -14
일치: True


In [6]:
# 3×3 행렬의 행렬식
C = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

det_C = np.linalg.det(C)
print('행렬 C:')
print(C)
print(f'\ndet(C) = {det_C:.2f}')

행렬 C:
[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]

det(C) = -306.00


### 2.2 특이행렬 (Singular Matrix)

In [7]:
# 행렬식이 0인 특이행렬 (역행렬 없음)
S = np.array([[1, 2, 3],
              [2, 4, 6],
              [3, 6, 9]])

print('특이행렬 S (두 번째 행 = 첫 번째 행 × 2):')
print(S)
print()

det_S = np.linalg.det(S)
print(f'det(S) = {det_S:.2e}  (0에 매우 가까움)')
print()

# 역행렬 시도
try:
    S_inv = np.linalg.inv(S)
    print('역행렬 (불안정):', S_inv)
except np.linalg.LinAlgError as e:
    print(f'❌ 오류: {e}')
    print('설명: det(S)=0이므로 역행렬이 존재하지 않습니다')

특이행렬 S (두 번째 행 = 첫 번째 행 × 2):
[[1 2 3]
 [2 4 6]
 [3 6 9]]

det(S) = 0.00e+00  (0에 매우 가까움)

❌ 오류: Singular matrix
설명: det(S)=0이므로 역행렬이 존재하지 않습니다


## 📚 3. 행렬의 랭크 (Rank)

### 3.1 랭크 계산

In [8]:
# 풀랭크 행렬
A = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

rank_A = np.linalg.matrix_rank(A)
print('풀랭크 행렬 A (단위행렬):')
print(A)
print(f'랭크: {rank_A} (= min(3, 3) = 3) ✅')
print()

풀랭크 행렬 A (단위행렬):
[[1 0 0]
 [0 1 0]
 [0 0 1]]
랭크: 3 (= min(3, 3) = 3) ✅



In [9]:
# 랭크가 낮은 행렬
B = np.array([[1, 2, 3],
              [2, 4, 6],
              [3, 6, 9]])

rank_B = np.linalg.matrix_rank(B)
print('랭크 부족 행렬 B (모든 행이 선형종속):')
print(B)
print(f'랭크: {rank_B}')
print('설명: 세 행이 모두 [1,2,3]의 배수이므로 랭크 = 1')
print()

랭크 부족 행렬 B (모든 행이 선형종속):
[[1 2 3]
 [2 4 6]
 [3 6 9]]
랭크: 1
설명: 세 행이 모두 [1,2,3]의 배수이므로 랭크 = 1



In [10]:
# 직사각형 행렬의 랭크
C = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

rank_C = np.linalg.matrix_rank(C)
print('직사각형 행렬 C (3×4):')
print(C)
print(f'랭크: {rank_C}')
print(f'최대 가능 랭크: min(3, 4) = 3')
print(f'실제 랭크: {rank_C} (선형종속성 존재)')

직사각형 행렬 C (3×4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
랭크: 2
최대 가능 랭크: min(3, 4) = 3
실제 랭크: 2 (선형종속성 존재)


## 📚 4. 선형 방정식 풀이

### 4.1 np.linalg.solve 사용

In [11]:
# 연립방정식 Ax = b 풀이
# 2x + 3y = 8
# x - 4y = -2

A = np.array([[2, 3],
              [1, -4]])
b = np.array([8, -2])

print('연립방정식:')
print('2x + 3y = 8')
print('x - 4y = -2')
print()

# 방법 1: np.linalg.solve
x = np.linalg.solve(A, b)
print('해 (np.linalg.solve):')
print(f'x = {x[0]:.2f}, y = {x[1]:.2f}')
print()

# 검증
result = A @ x
print('검증 (Ax):')
print(result)
print(f'b와 일치: {np.allclose(result, b)}')
print()

연립방정식:
2x + 3y = 8
x - 4y = -2

해 (np.linalg.solve):
x = 2.36, y = 1.09

검증 (Ax):
[ 8. -2.]
b와 일치: True



In [12]:
# 방법 2: 역행렬 사용
A_inv = np.linalg.inv(A)
x2 = A_inv @ b

print('해 (역행렬 사용):')
print(f'x = {x2[0]:.2f}, y = {x2[1]:.2f}')
print()

print(f'두 방법의 결과 일치: {np.allclose(x, x2)}')
print()
print('※ 실무에서는 np.linalg.solve가 더 효율적이고 안정적입니다')

해 (역행렬 사용):
x = 2.36, y = 1.09

두 방법의 결과 일치: True

※ 실무에서는 np.linalg.solve가 더 효율적이고 안정적입니다


### 4.2 과소/과대 결정 시스템

In [13]:
# 과대 결정 시스템 (방정식 개수 > 미지수 개수)
# 해가 없거나 최소제곱해 필요

A_over = np.array([[1, 1],
                   [1, 2],
                   [1, 3]])
b_over = np.array([2, 3, 4])

print('과대 결정 시스템 (3개 방정식, 2개 미지수):')
print('A:')
print(A_over)
print(f'b: {b_over}')
print()

# np.linalg.lstsq로 최소제곱해
x_lstsq, residuals, rank, s = np.linalg.lstsq(A_over, b_over, rcond=None)
print('최소제곱해:')
print(x_lstsq)
print(f'\n잔차 (residual): {residuals}')

과대 결정 시스템 (3개 방정식, 2개 미지수):
A:
[[1 1]
 [1 2]
 [1 3]]
b: [2 3 4]

최소제곱해:
[1. 1.]

잔차 (residual): [0.]


## 🔥 연습 문제

### 문제 1: 역행렬 계산 및 검증

In [15]:
# TODO: 다음 행렬의 역행렬을 구하고 A @ A⁻¹ = I 임을 확인하세요
A = np.array([[3, 1],
              [5, 2]])

# 여기에 코드 작성
A_inb=np.linalg.inv(A)
c=A@A_inb
print("A @ A⁻¹:",np.allclose(c, np.eye(2)))

A @ A⁻¹: True


In [ ]:
# 해답
A = np.array([[3, 1],
              [5, 2]])

print('행렬 A:')
print(A)
print()

# 역행렬 계산
A_inv = np.linalg.inv(A)
print('역행렬 A⁻¹:')
print(A_inv)
print()

# 검증
identity = A @ A_inv
print('A @ A⁻¹:')
print(identity)
print()

print(f'단위행렬과 일치: {np.allclose(identity, np.eye(2))}')

# 행렬식 확인
det_A = np.linalg.det(A)
print(f'\ndet(A) = {det_A:.2f} (≠ 0이므로 역행렬 존재 ✅)')

행렬 A:
[[3 1]
 [5 2]]

역행렬 A⁻¹:
[[ 2. -1.]
 [-5.  3.]]

A @ A⁻¹:
[[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]

단위행렬과 일치: True

det(A) = 1.00 (≠ 0이므로 역행렬 존재 ✅)


### 문제 2: 랭크 확인

In [ ]:
# TODO: 다음 행렬들의 랭크를 구하고 설명하세요
import numpy as np
B1 = np.array([[1, 2, 3],
               [2, 4, 6],
               [3, 6, 9]])

B2 = np.array([[1, 0, 0],
               [0, 1, 1],
               [0, 1, 1]])

B3 = np.array([[1, 2],
               [3, 4],
               [5, 6]])

# 여기에 코드 작성
print(np.linalg.matrix_rank(B1))
print(np.linalg.matrix_rank(B2))
print(np.linalg.matrix_rank(B3))


1
2
2
2


In [ ]:
# 해답
B1 = np.array([[1, 2, 3],
               [2, 4, 6],
               [3, 6, 9]])
B2 = np.array([ [1, 0, 0],
               [0, 1, 1],
               [0, 1, 1]])
B3 = np.array([[1, 2],
               [3, 4],
               [5, 6]])

print('B1 (모든 행이 선형종속):')
print(B1)
print(f'랭크: {np.linalg.matrix_rank(B1)}')
print('설명: 모든 행이 [1,2,3]의 배수\n')

print('B2 (두 번째와 세 번째 행이 동일):')
print(B2)
print(f'랭크: {np.linalg.matrix_rank(B2)}')
print('설명: 선형독립인 행이 2개\n')

print('B3 (직사각형, 풀랭크):')
print(B3)
print(f'랭크: {np.linalg.matrix_rank(B3)}')
print(f'최대 가능 랭크: min(3, 2) = 2')
print('설명: 두 열이 모두 선형독립')

B1 (모든 행이 선형종속):
[[1 2 3]
 [2 4 6]
 [3 6 9]]
랭크: 1
설명: 모든 행이 [1,2,3]의 배수

B2 (두 번째와 세 번째 행이 동일):
[[1 0 0]
 [0 1 1]
 [0 1 1]]
랭크: 2
설명: 선형독립인 행이 2개

B3 (직사각형, 풀랭크):
[[1 2]
 [3 4]
 [5 6]]
랭크: 2
최대 가능 랭크: min(3, 2) = 2
설명: 두 열이 모두 선형독립


## 📝 복습 및 팁

### 핵심 정리

| 개념 | 의미 | NumPy 함수 | 조건 |
|------|------|-----------|------|
| 역행렬 | A·A⁻¹ = I | `np.linalg.inv()` | det(A) ≠ 0 |
| 행렬식 | 부피 스케일 | `np.linalg.det()` | 정방행렬 |
| 랭크 | 선형독립 차원 | `np.linalg.matrix_rank()` | 모든 행렬 |
| 선형방정식 | Ax = b | `np.linalg.solve()` | A가 정방/비특이 |

### 주요 개념
1. **가역행렬**: det(A) ≠ 0, 풀랭크
2. **특이행렬**: det(A) = 0, 역행렬 없음
3. **풀랭크**: rank = min(행, 열)

### 딥러닝 연관성
- 역행렬: 이론적 이해 (실제로는 경사하강 사용)
- 행렬식: Hessian 분석
- 랭크: 모델 표현력 분석